# SPDX-License-Identifier: MIT
# Jobs to run CI
name: CI
on:
  push:
    branches:
    - main
    - release*
    tags:
    - v*
  pull_request:
    branches:
    - main

env:
  GO_VERSION: "^1.17"

jobs:
  ci-golangci-lint:
    name: ci-golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Checkout code
      uses: actions/checkout@v3.1.0

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: latest

  ci-build:
    name: ci-build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Checkout code
      uses: actions/checkout@v3.1.0

    - name: make build
      run: |
        make build

  ci-manifests-generate:
    name: ci-manifests-generate
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Checkout code
      uses: actions/checkout@v3.1.0

    - name: make manifests generate
      run: |
        make manifests generate
        git diff || (echo "run 'make manifests generate' and commit changes"; exit 1)

  ci-docs:
    name: ci-docs
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Checkout code
      uses: actions/checkout@v3.1.0

    - name: make docs doccheck
      run: |
        make docs doccheck

  ci-spdxcheck:
    name: ci-spdxcheck
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Checkout code
      uses: actions/checkout@v3.1.0

    - name: make spdxcheck
      run: |
        make spdxcheck

  ci-fmt-vet:
    name: ci-fmt-vet
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Checkout code
      uses: actions/checkout@v3.1.0

    - name: make fmt vet
      run: |
        make fmt vet
        git diff || (echo "run 'make fmt vet' and commit changes"; exit 1)
